# values.yaml

# Đây là cấu trúc dữ liệu chính
renderConfig:
  services: {}
  # Ví dụ mẫu (để bạn hình dung):
  # vac-ai-core-audio:
  #   host: vac-ai-core-audio.service-core.svc.cluster.local
  #   port: 80
  #   paths: 
  #     - /audio
  #   strip_path: true
  #   plugins: 
  #     - my-rate-limit

# Tên class của Ingress Controller (khớp với phần cài đặt Kong)
ingressClassName: kong